drop table if exists review_movies;

create table review_movies
(
reviewer_id int not null,
reviewer_Name varchar(200) not null,
reviewer_type varchar(50),
movie_name varchar(200),
movie_rating int not null,
movie_comments varchar(50),
primary key(reviewer_id)
)
;
INSERT INTO review_movies values(1,'GORDON','Spouse','The lion king',1,'Worst');
INSERT INTO review_movies values(2,'HALL','Daughter','IT Chapter two',4,'Good');
INSERT INTO review_movies values(3,'BENNETT','Mom','The lion king',5,'Excellent');
INSERT INTO review_movies values(4,'DIXON','Friend','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(5,'WHITE','Spouse','Fast and Furious',5,'');
INSERT INTO review_movies values(6,'MURRAY','Dad','Angel has fallen',3,'');
INSERT INTO review_movies values(7,'STEVENS','Spouse','Ready or not',3,'');
INSERT INTO review_movies values(8,'PHILLIPS','Dad','The lion king',1,'');
INSERT INTO review_movies values(9,'WELLS','Spouse','Fast and Furious',3,'');
INSERT INTO review_movies values(10,'HICKS','Mom','Ready or not',4,'');
INSERT INTO review_movies values(11,'HUNT','Spouse','Fast and Furious',5,'');
INSERT INTO review_movies values(12,'BAKER','Dad','IT Chapter two',4,'');
INSERT INTO review_movies values(13,'PERRY','Spouse','Good Boys',3,'Average');
INSERT INTO review_movies values(14,'WEBB','Son','The lion king',5,'Excellent');
INSERT INTO review_movies values(15,'PATTERSON','Mom','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(16,'HOLMES','Friend','Ready or not',1,'Worst');
INSERT INTO review_movies values(17,'HUNT','Friend','IT Chapter two',3,'Average');
INSERT INTO review_movies values(18,'WELLS','Daughter','Good Boys',2,'Poor');
INSERT INTO review_movies values(19,'ROSE','Friend','Good Boys',3,'Average');
INSERT INTO review_movies values(20,'MILLS','Spouse','Angel has fallen',3,'Average');
INSERT INTO review_movies values(21,'WRIGHT','Son','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(22,'HERNANDEZ','Daughter','Angel has fallen',3,'Average');
INSERT INTO review_movies values(23,'BARNES','Dad','Angel has fallen',3,'Average');
INSERT INTO review_movies values(24,'HAMILTON','Daughter','Angel has fallen',4,'Good');
INSERT INTO review_movies values(25,'HILL','Mom','Good Boys',3,'Average');
INSERT INTO review_movies values(26,'GOMEZ','Daughter','The lion king',5,'Excellent');
INSERT INTO review_movies values(27,'PORTER','Dad','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(28,'GREEN','Friend','Fast and Furious',3,'Average');
INSERT INTO review_movies values(29,'HICKS','Friend','Fast and Furious',3,'Average');
INSERT INTO review_movies values(30,'SCOTT','Mom','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(31,'DAVIS','Dad','Good Boys',3,'Average');
INSERT INTO review_movies values(32,'NICHOLS','Daughter','Good Boys',4,'Good');
INSERT INTO review_movies values(33,'DANIELS','Daughter','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(34,'HERNANDEZ','Mom','Fast and Furious',4,'Good');
INSERT INTO review_movies values(35,'CRAWFORD','Dad','Ready or not',5,'Excellent');
INSERT INTO review_movies values(36,'TAYLOR','Son','Good Boys',3,'Average');
INSERT INTO review_movies values(37,'ROSS','Friend','IT Chapter two',2,'Poor');
INSERT INTO review_movies values(38,'PHILLIPS','','Angel has fallen',3,'Average');
INSERT INTO review_movies values(39,'SMITH','','The lion king',1,'Worst');
INSERT INTO review_movies values(40,'PRICE','','Good Boys',4,'Good');
INSERT INTO review_movies values(41,'MITCHELL','','The lion king',4,'Good');
INSERT INTO review_movies values(42,'GARCIA','','The lion king',5,'Excellent');
INSERT INTO review_movies values(43,'TURNER','Son','Ready or not',3,'Average');
INSERT INTO review_movies values(44,'HILL','Dad','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(45,'ALEXANDER','Daughter','Ready or not',4,'Good');
INSERT INTO review_movies values(46,'ROBERTSON','Dad','Ready or not',4,'Good');
INSERT INTO review_movies values(47,'RAMIREZ','Mom','Angel has fallen',4,'Good');
INSERT INTO review_movies values(48,'WEBB','Spouse','Ready or not',3,'Average');
INSERT INTO review_movies values(49,'MITCHELL','Daughter','Good Boys',5,'Excellent');
INSERT INTO review_movies values(50,'BARNES','Friend','Good Boys',1,'Worst');
INSERT INTO review_movies values(51,'ALLEN','Mom','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(52,'DIAZ','Mom','Good Boys',4,'Good');
INSERT INTO review_movies values(53,'STONE','Daughter','Ready or not',2,'Poor');
INSERT INTO review_movies values(54,'JACKSON','Son','Ready or not',2,'Poor');
INSERT INTO review_movies values(55,'TORRES','Daughter','Ready or not',4,'Good');
INSERT INTO review_movies values(56,'BAILEY','Mom','The lion king',1,'Worst');
INSERT INTO review_movies values(57,'BELL','Son','Good Boys',2,'Poor');
INSERT INTO review_movies values(58,'FREEMAN','Dad','Good Boys',4,'Good');
INSERT INTO review_movies values(59,'HAMILTON','Spouse','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(60,'WEBB','Daughter','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(61,'WEBB','Mom','The lion king',3,'Average');
INSERT INTO review_movies values(62,'COLE','Friend','Fast and Furious',4,'Good');
INSERT INTO review_movies values(63,'KELLY','Dad','Good Boys',1,'Worst');
INSERT INTO review_movies values(64,'PEREZ','Spouse','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(65,'KENNEDY','Mom','Ready or not',2,'Poor');
INSERT INTO review_movies values(66,'DIXON','Mom','The lion king',2,'Poor');
INSERT INTO review_movies values(67,'HAWKINS','Friend','Good Boys',3,'Average');
INSERT INTO review_movies values(68,'COLEMAN','Mom','Angel has fallen',4,'Good');
INSERT INTO review_movies values(69,'HICKS','','Angel has fallen',3,'Average');
INSERT INTO review_movies values(70,'STONE','','Fast and Furious',3,'Average');
INSERT INTO review_movies values(71,'WILLIAMS','','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(72,'ADAMS','','Ready or not',4,'Good');
INSERT INTO review_movies values(73,'GONZALEZ','Daughter','The lion king',1,'Worst');
INSERT INTO review_movies values(74,'FERGUSON','Daughter','The lion king',4,'Good');
INSERT INTO review_movies values(75,'LEWIS','Son','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(76,'PETERSON','Dad','Good Boys',3,'Average');
INSERT INTO review_movies values(77,'GORDON','Mom','IT Chapter two',3,'Average');
INSERT INTO review_movies values(78,'HAYES','Mom','IT Chapter two',4,'Good');
INSERT INTO review_movies values(79,'GRAHAM','Spouse','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(80,'HERNANDEZ','Son','Ready or not',5,'Excellent');
INSERT INTO review_movies values(81,'HENRY','Son','Good Boys',5,'Excellent');
INSERT INTO review_movies values(82,'FISHER','Mom','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(83,'CLARK','Mom','The lion king',3,'Average');
INSERT INTO review_movies values(84,'WARD','Mom','Good Boys',3,'Average');
INSERT INTO review_movies values(85,'PRICE','Daughter','Good Boys',2,'Poor');
INSERT INTO review_movies values(86,'TUCKER','Mom','Fast and Furious',4,'Good');
INSERT INTO review_movies values(87,'LEWIS','Son','Ready or not',1,'Worst');
INSERT INTO review_movies values(88,'RAMOS','Mom','Good Boys',2,'Poor');
INSERT INTO review_movies values(89,'JAMES','Mom','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(90,'LEWIS','Dad','Angel has fallen',3,'Average');
INSERT INTO review_movies values(91,'JACKSON','Daughter','Ready or not',4,'Good');
INSERT INTO review_movies values(92,'JONES','Mom','Ready or not',2,'Poor');
INSERT INTO review_movies values(93,'CAMPBELL','Dad','IT Chapter two',4,'Good');
INSERT INTO review_movies values(94,'SANCHEZ','Friend','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(95,'PRICE','Mom','The lion king',3,'Average');
INSERT INTO review_movies values(96,'DUNN','Spouse','Angel has fallen',4,'Good');
INSERT INTO review_movies values(97,'GRIFFIN','Friend','Ready or not',5,'Excellent');
INSERT INTO review_movies values(98,'HARRISON','Friend','The lion king',5,'Excellent');
INSERT INTO review_movies values(99,'JACKSON','Spouse','Good Boys',3,'Average');
INSERT INTO review_movies values(100,'KNIGHT','Spouse','Ready or not',4,'Good');
INSERT INTO review_movies values(101,'REYNOLDS','Mom','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(102,'RIVERA','Mom','The lion king',1,'Worst');
INSERT INTO review_movies values(103,'WATSON','Daughter','The lion king',4,'Good');
INSERT INTO review_movies values(104,'GOMEZ','Mom','The lion king',2,'Poor');
INSERT INTO review_movies values(105,'RICE','Dad','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(106,'WELLS','Daughter','Good Boys',5,'Excellent');
INSERT INTO review_movies values(107,'FLORES','Spouse','Fast and Furious',3,'Average');
INSERT INTO review_movies values(108,'GREEN','Spouse','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(109,'HOWARD','Daughter','Ready or not',3,'Average');
INSERT INTO review_movies values(110,'REYNOLDS','Son','Angel has fallen',4,'Good');
INSERT INTO review_movies values(111,'CRUZ','Friend','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(112,'FERGUSON','Mom','Good Boys',5,'Excellent');
INSERT INTO review_movies values(113,'BUTLER','Son','Good Boys',5,'Excellent');
INSERT INTO review_movies values(114,'BRYANT','Son','Ready or not',5,'Excellent');
INSERT INTO review_movies values(115,'COLE','Dad','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(116,'DUNN','Son','Good Boys',4,'Good');
INSERT INTO review_movies values(117,'PEREZ','Daughter','Fast and Furious',4,'Good');
INSERT INTO review_movies values(118,'ADAMS','Mom','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(119,'COLLINS','Son','Angel has fallen',4,'Good');
INSERT INTO review_movies values(120,'LOPEZ','Friend','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(121,'GOMEZ','Mom','Good Boys',1,'Worst');
INSERT INTO review_movies values(122,'ADAMS','Dad','The lion king',1,'Worst');
INSERT INTO review_movies values(123,'JOHNSON','Son','Fast and Furious',4,'Good');
INSERT INTO review_movies values(124,'BROOKS','Mom','Fast and Furious',4,'Good');
INSERT INTO review_movies values(125,'LONG','Spouse','Ready or not',4,'Good');
INSERT INTO review_movies values(126,'HUNT','Dad','The lion king',4,'Good');
INSERT INTO review_movies values(127,'GRAHAM','Daughter','Good Boys',4,'Good');
INSERT INTO review_movies values(128,'WHITE','Mom','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(129,'HICKS','Son','Good Boys',4,'Good');
INSERT INTO review_movies values(130,'FLORES','Mom','The lion king',4,'Good');
INSERT INTO review_movies values(131,'WOOD','Mom','Angel has fallen',4,'Good');
INSERT INTO review_movies values(132,'HENRY','Mom','Angel has fallen',3,'Average');
INSERT INTO review_movies values(133,'GIBSON','Spouse','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(134,'OWENS','Son','Ready or not',3,'Average');
INSERT INTO review_movies values(135,'JACKSON','Daughter','Ready or not',4,'Good');
INSERT INTO review_movies values(136,'JACKSON','Spouse','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(137,'DIAZ','Daughter','Good Boys',1,'Worst');
INSERT INTO review_movies values(138,'GREEN','Friend','Good Boys',3,'Average');
INSERT INTO review_movies values(139,'MOORE','Mom','Ready or not',4,'Good');
INSERT INTO review_movies values(140,'LEE','Daughter','Ready or not',4,'Good');
INSERT INTO review_movies values(141,'STONE','Dad','The lion king',5,'Excellent');
INSERT INTO review_movies values(142,'GOMEZ','Son','Ready or not',1,'Worst');
INSERT INTO review_movies values(143,'LEWIS','Dad','Fast and Furious',3,'Average');
INSERT INTO review_movies values(144,'PALMER','Mom','Good Boys',4,'Good');
INSERT INTO review_movies values(145,'BLACK','Dad','Angel has fallen',4,'Good');
INSERT INTO review_movies values(146,'OWENS','Spouse','Ready or not',1,'Worst');
INSERT INTO review_movies values(147,'CAMPBELL','Mom','Ready or not',4,'Good');
INSERT INTO review_movies values(148,'MORRIS','Mom','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(149,'BAKER','Dad','Ready or not',1,'Worst');
INSERT INTO review_movies values(150,'HOWARD','Spouse','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(151,'WALLACE','Spouse','The lion king',1,'Worst');
INSERT INTO review_movies values(152,'BLACK','Daughter','The lion king',5,'Excellent');
INSERT INTO review_movies values(153,'ALLEN','Friend','The lion king',2,'Poor');
INSERT INTO review_movies values(154,'PETERSON','Daughter','Ready or not',2,'Poor');
INSERT INTO review_movies values(155,'BROOKS','Son','The lion king',2,'Poor');
INSERT INTO review_movies values(156,'BURNS','Friend','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(157,'BROWN','Mom','Angel has fallen',4,'Good');
INSERT INTO review_movies values(158,'BOYD','Friend','Fast and Furious',3,'Average');
INSERT INTO review_movies values(159,'GRAY','Son','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(160,'GREEN','Daughter','Ready or not',5,'Excellent');
INSERT INTO review_movies values(161,'LOPEZ','Spouse','The lion king',2,'Poor');
INSERT INTO review_movies values(162,'PETERSON','Son','The lion king',5,'Excellent');
INSERT INTO review_movies values(163,'ORTIZ','Friend','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(164,'NICHOLS','Son','Angel has fallen',4,'Good');
INSERT INTO review_movies values(165,'GRAY','Dad','Good Boys',1,'Worst');
INSERT INTO review_movies values(166,'BROOKS','Friend','Good Boys',4,'Good');
INSERT INTO review_movies values(167,'RICE','Daughter','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(168,'MORALES','Mom','Ready or not',3,'Average');
INSERT INTO review_movies values(169,'JOHNSON','Daughter','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(170,'WALLACE','Friend','IT Chapter two',2,'Poor');
INSERT INTO review_movies values(171,'ELLIS','Dad','Ready or not',5,'Excellent');
INSERT INTO review_movies values(172,'PORTER','Friend','Good Boys',2,'Poor');
INSERT INTO review_movies values(173,'COLEMAN','Mom','Fast and Furious',3,'Average');
INSERT INTO review_movies values(174,'RODRIGUEZ','Spouse','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(175,'PHILLIPS','Mom','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(176,'WASHINGTON','Daughter','Good Boys',1,'Worst');
INSERT INTO review_movies values(177,'KELLY','Friend','Ready or not',5,'Excellent');
INSERT INTO review_movies values(178,'HALL','Spouse','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(179,'SHAW','Mom','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(180,'TAYLOR','Son','Good Boys',3,'Average');
INSERT INTO review_movies values(181,'DUNN','Mom','Ready or not',3,'Average');
INSERT INTO review_movies values(182,'COLE','Spouse','Good Boys',1,'Worst');
INSERT INTO review_movies values(183,'ROBERTSON','Spouse','Fast and Furious',4,'Good');
INSERT INTO review_movies values(184,'MASON','Mom','The lion king',2,'Poor');
INSERT INTO review_movies values(185,'COX','Mom','Ready or not',1,'Worst');
INSERT INTO review_movies values(186,'MOORE','Friend','Good Boys',1,'Worst');
INSERT INTO review_movies values(187,'GORDON','Daughter','Ready or not',5,'Excellent');
INSERT INTO review_movies values(188,'ELLIS','Daughter','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(189,'RICE','Mom','The lion king',1,'Worst');
INSERT INTO review_movies values(190,'THOMAS','Mom','Ready or not',3,'Average');
INSERT INTO review_movies values(191,'HARRIS','Friend','Fast and Furious',3,'Average');
INSERT INTO review_movies values(192,'SULLIVAN','Son','Fast and Furious',4,'Good');
INSERT INTO review_movies values(193,'THOMPSON','Spouse','The lion king',2,'Poor');
INSERT INTO review_movies values(194,'NELSON','Son','Good Boys',2,'Poor');
INSERT INTO review_movies values(195,'THOMPSON','Son','IT Chapter two',4,'Good');
INSERT INTO review_movies values(196,'WRIGHT','Dad','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(197,'ANDERSON','Spouse','Angel has fallen',4,'Good');
INSERT INTO review_movies values(198,'SANDERS','Son','The lion king',4,'Good');
INSERT INTO review_movies values(199,'HAMILTON','Dad','Ready or not',1,'Worst');
INSERT INTO review_movies values(200,'WILLIAMS','Dad','Good Boys',1,'Worst');
INSERT INTO review_movies values(201,'WARREN','Daughter','Good Boys',3,'Average');
INSERT INTO review_movies values(202,'COLEMAN','Son','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(203,'THOMPSON','Mom','Ready or not',4,'Good');
INSERT INTO review_movies values(204,'GONZALES','Son','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(205,'GRAHAM','Spouse','Ready or not',2,'Poor');
INSERT INTO review_movies values(206,'ROSS','Son','IT Chapter two',2,'Poor');
INSERT INTO review_movies values(207,'GRIFFIN','Son','IT Chapter two',4,'Good');
INSERT INTO review_movies values(208,'HILL','Son','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(209,'WRIGHT','Friend','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(210,'SIMPSON','Mom','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(211,'ANDERSON','Spouse','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(212,'GIBSON','Friend','Good Boys',5,'Excellent');
INSERT INTO review_movies values(213,'JOHNSON','Mom','Ready or not',4,'Good');
INSERT INTO review_movies values(214,'MORRIS','Spouse','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(215,'MITCHELL','Friend','Good Boys',5,'Excellent');
INSERT INTO review_movies values(216,'KING','Dad','Good Boys',5,'Excellent');
INSERT INTO review_movies values(217,'NELSON','Friend','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(218,'ROBERTSON','Dad','The lion king',4,'Good');
INSERT INTO review_movies values(219,'JACKSON','Dad','IT Chapter two',4,'Good');
INSERT INTO review_movies values(220,'ROSS','Dad','Ready or not',5,'Excellent');
INSERT INTO review_movies values(221,'ROSS','Daughter','Good Boys',5,'Excellent');
INSERT INTO review_movies values(222,'RICHARDSON','Daughter','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(223,'RIVERA','Daughter','Fast and Furious',4,'Good');
INSERT INTO review_movies values(224,'TURNER','Mom','Ready or not',4,'Good');
INSERT INTO review_movies values(225,'STEWART','Dad','Angel has fallen',3,'Average');
INSERT INTO review_movies values(226,'RAMOS','Daughter','The lion king',2,'Poor');
INSERT INTO review_movies values(227,'WILLIAMS','Spouse','Fast and Furious',3,'Average');
INSERT INTO review_movies values(228,'ROBINSON','Son','Good Boys',4,'Good');
INSERT INTO review_movies values(229,'CLARK','Spouse','Angel has fallen',3,'Average');
INSERT INTO review_movies values(230,'BRYANT','Mom','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(231,'DIAZ','Son','Good Boys',1,'Worst');
INSERT INTO review_movies values(232,'COLLINS','Friend','The lion king',1,'Worst');
INSERT INTO review_movies values(233,'OWENS','Spouse','The lion king',1,'Worst');
INSERT INTO review_movies values(234,'EVANS','Son','Ready or not',4,'Good');
INSERT INTO review_movies values(235,'DANIELS','Dad','Good Boys',1,'Worst');
INSERT INTO review_movies values(236,'PORTER','Mom','IT Chapter two',4,'Good');
INSERT INTO review_movies values(237,'SANCHEZ','Spouse','The lion king',4,'Good');
INSERT INTO review_movies values(238,'PETERSON','Daughter','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(239,'PALMER','Dad','Angel has fallen',3,'Average');
INSERT INTO review_movies values(240,'MILLER','Son','Good Boys',4,'Good');
INSERT INTO review_movies values(241,'KING','Daughter','Ready or not',5,'Excellent');
INSERT INTO review_movies values(242,'DAVIS','Daughter','Fast and Furious',4,'Good');
INSERT INTO review_movies values(243,'THOMPSON','Mom','The lion king',1,'Worst');
INSERT INTO review_movies values(244,'WOODS','Dad','Fast and Furious',4,'Good');
INSERT INTO review_movies values(245,'TAYLOR','Friend','Angel has fallen',4,'Good');
INSERT INTO review_movies values(246,'WILLIAMS','Dad','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(247,'BROOKS','Mom','Good Boys',5,'Excellent');
INSERT INTO review_movies values(248,'PORTER','Spouse','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(249,'WOOD','Friend','Good Boys',2,'Poor');
INSERT INTO review_movies values(250,'COOPER','Friend','Ready or not',1,'Worst');
INSERT INTO review_movies values(251,'PATTERSON','Son','The lion king',4,'Good');
INSERT INTO review_movies values(252,'WELLS','Spouse','The lion king',2,'Poor');
INSERT INTO review_movies values(253,'JONES','Dad','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(254,'HICKS','Son','Ready or not',2,'Poor');
INSERT INTO review_movies values(255,'CRAWFORD','Mom','Angel has fallen',4,'Good');
INSERT INTO review_movies values(256,'KNIGHT','Dad','Good Boys',4,'Good');
INSERT INTO review_movies values(257,'WEBB','Son','The lion king',1,'Worst');
INSERT INTO review_movies values(258,'FERGUSON','Daughter','Ready or not',4,'Good');
INSERT INTO review_movies values(259,'HICKS','Dad','Good Boys',2,'Poor');
INSERT INTO review_movies values(260,'MARSHALL','Friend','Good Boys',5,'Excellent');
INSERT INTO review_movies values(261,'HUNTER','Spouse','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(262,'BARNES','Son','Ready or not',1,'Worst');
INSERT INTO review_movies values(263,'ROBERTSON','Mom','Angel has fallen',3,'Average');
INSERT INTO review_movies values(264,'PATTERSON','Spouse','The lion king',3,'Average');
INSERT INTO review_movies values(265,'MURPHY','Mom','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(266,'HOLMES','Friend','Angel has fallen',3,'Average');
INSERT INTO review_movies values(267,'ALEXANDER','Friend','Ready or not',3,'Average');
INSERT INTO review_movies values(268,'PARKER','Daughter','The lion king',3,'Average');
INSERT INTO review_movies values(269,'MILLER','Mom','Good Boys',3,'Average');
INSERT INTO review_movies values(270,'FREEMAN','Mom','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(271,'SANCHEZ','Daughter','Ready or not',5,'Excellent');
INSERT INTO review_movies values(272,'RUSSELL','Dad','Fast and Furious',3,'Average');
INSERT INTO review_movies values(273,'BENNETT','Mom','IT Chapter two',2,'Poor');
INSERT INTO review_movies values(274,'NICHOLS','Friend','The lion king',2,'Poor');
INSERT INTO review_movies values(275,'WEST','Mom','The lion king',1,'Worst');
INSERT INTO review_movies values(276,'BAILEY','Daughter','The lion king',2,'Poor');
INSERT INTO review_movies values(277,'ROSE','Daughter','IT Chapter two',3,'Average');
INSERT INTO review_movies values(278,'JENKINS','Spouse','Ready or not',2,'Poor');
INSERT INTO review_movies values(279,'BURNS','Son','IT Chapter two',3,'Average');
INSERT INTO review_movies values(280,'LONG','Friend','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(281,'PETERSON','Son','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(282,'HUGHES','Daughter','Fast and Furious',3,'Average');
INSERT INTO review_movies values(283,'KING','Daughter','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(284,'TURNER','Friend','Ready or not',1,'Worst');
INSERT INTO review_movies values(285,'STONE','Dad','Ready or not',3,'Average');
INSERT INTO review_movies values(286,'RODRIGUEZ','Daughter','Good Boys',1,'Worst');
INSERT INTO review_movies values(287,'JENKINS','Spouse','Ready or not',2,'Poor');
INSERT INTO review_movies values(288,'CRAWFORD','Son','Ready or not',4,'Good');
INSERT INTO review_movies values(289,'ROSE','Son','Fast and Furious',3,'Average');
INSERT INTO review_movies values(290,'BAILEY','Daughter','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(291,'ANDERSON','Friend','The lion king',1,'Worst');
INSERT INTO review_movies values(292,'HOLMES','Friend','Good Boys',2,'Poor');
INSERT INTO review_movies values(293,'EDWARDS','Spouse','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(294,'MILLER','Friend','The lion king',3,'Average');
INSERT INTO review_movies values(295,'BELL','Son','The lion king',2,'Poor');
INSERT INTO review_movies values(296,'ROBINSON','Son','Angel has fallen',4,'Good');
INSERT INTO review_movies values(297,'RUSSELL','Son','The lion king',1,'Worst');
INSERT INTO review_movies values(298,'STONE','Friend','Ready or not',1,'Worst');
INSERT INTO review_movies values(299,'EDWARDS','Daughter','The lion king',2,'Poor');
INSERT INTO review_movies values(300,'RIVERA','Mom','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(301,'BROOKS','Dad','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(302,'GRIFFIN','Spouse','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(303,'RICHARDSON','Daughter','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(304,'KENNEDY','Friend','Good Boys',2,'Poor');
INSERT INTO review_movies values(305,'BROOKS','Daughter','Good Boys',4,'Good');
INSERT INTO review_movies values(306,'REED','Dad','Good Boys',5,'Excellent');
INSERT INTO review_movies values(307,'YOUNG','Son','IT Chapter two',4,'Good');
INSERT INTO review_movies values(308,'RICHARDSON','Son','IT Chapter two',4,'Good');
INSERT INTO review_movies values(309,'GOMEZ','Spouse','Ready or not',1,'Worst');
INSERT INTO review_movies values(310,'BROOKS','Dad','Angel has fallen',4,'Good');
INSERT INTO review_movies values(311,'WOODS','Son','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(312,'BAKER','Son','Ready or not',3,'Average');
INSERT INTO review_movies values(313,'GRIFFIN','Spouse','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(314,'ROBINSON','Daughter','The lion king',2,'Poor');
INSERT INTO review_movies values(315,'SMITH','Dad','The lion king',3,'Average');
INSERT INTO review_movies values(316,'TUCKER','Spouse','IT Chapter two',3,'Average');
INSERT INTO review_movies values(317,'MARTINEZ','Spouse','Ready or not',4,'Good');
INSERT INTO review_movies values(318,'MITCHELL','Son','Ready or not',1,'Worst');
INSERT INTO review_movies values(319,'KING','Spouse','Good Boys',2,'Poor');
INSERT INTO review_movies values(320,'DIXON','Spouse','Fast and Furious',3,'Average');
INSERT INTO review_movies values(321,'MYERS','Daughter','Good Boys',1,'Worst');
INSERT INTO review_movies values(322,'COLE','Friend','IT Chapter two',2,'Poor');
INSERT INTO review_movies values(323,'PETERSON','Mom','Good Boys',1,'Worst');
INSERT INTO review_movies values(324,'WEBB','Spouse','IT Chapter two',2,'Poor');
INSERT INTO review_movies values(325,'FISHER','Mom','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(326,'DANIELS','Mom','The lion king',5,'Excellent');
INSERT INTO review_movies values(327,'SCOTT','Son','IT Chapter two',3,'Average');
INSERT INTO review_movies values(328,'BELL','Friend','Ready or not',1,'Worst');
INSERT INTO review_movies values(329,'FOSTER','Friend','The lion king',5,'Excellent');
INSERT INTO review_movies values(330,'ADAMS','Son','The lion king',1,'Worst');
INSERT INTO review_movies values(331,'STEVENS','Dad','The lion king',3,'Average');
INSERT INTO review_movies values(332,'WALLACE','Mom','Ready or not',5,'Excellent');
INSERT INTO review_movies values(333,'MILLER','Mom','The lion king',1,'Worst');
INSERT INTO review_movies values(334,'GORDON','Mom','IT Chapter two',4,'Good');
INSERT INTO review_movies values(335,'RUSSELL','Son','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(336,'WALLACE','Mom','Fast and Furious',4,'Good');
INSERT INTO review_movies values(337,'GARCIA','Daughter','Fast and Furious',3,'Average');
INSERT INTO review_movies values(338,'PERRY','Son','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(339,'WALLACE','Spouse','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(340,'MARTINEZ','Spouse','IT Chapter two',4,'Good');
INSERT INTO review_movies values(341,'BOYD','Mom','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(342,'WATSON','Mom','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(343,'MORRIS','Spouse','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(344,'HAYES','Daughter','Fast and Furious',4,'Good');
INSERT INTO review_movies values(345,'GARCIA','Daughter','The lion king',1,'Worst');
INSERT INTO review_movies values(346,'WILLIAMS','Daughter','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(347,'ROSE','Mom','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(348,'WOODS','Son','IT Chapter two',2,'Poor');
INSERT INTO review_movies values(349,'KING','Friend','Fast and Furious',4,'Good');
INSERT INTO review_movies values(350,'JAMES','Spouse','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(351,'WRIGHT','Daughter','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(352,'WALKER','Son','Good Boys',4,'Good');
INSERT INTO review_movies values(353,'BELL','Spouse','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(354,'SANDERS','Mom','Good Boys',2,'Poor');
INSERT INTO review_movies values(355,'HILL','Spouse','Angel has fallen',4,'Good');
INSERT INTO review_movies values(356,'LONG','Son','Good Boys',2,'Poor');
INSERT INTO review_movies values(357,'TAYLOR','Friend','Angel has fallen',4,'Good');
INSERT INTO review_movies values(358,'COLEMAN','Daughter','The lion king',1,'Worst');
INSERT INTO review_movies values(359,'ELLIS','Son','IT Chapter two',4,'Good');
INSERT INTO review_movies values(360,'GRAY','Friend','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(361,'BUTLER','Mom','Ready or not',3,'Average');
INSERT INTO review_movies values(362,'MURRAY','Friend','Fast and Furious',3,'Average');
INSERT INTO review_movies values(363,'COX','Daughter','The lion king',2,'Poor');
INSERT INTO review_movies values(364,'HICKS','Spouse','Fast and Furious',4,'Good');
INSERT INTO review_movies values(365,'WATSON','Mom','The lion king',3,'Average');
INSERT INTO review_movies values(366,'DAVIS','Spouse','Good Boys',4,'Good');
INSERT INTO review_movies values(367,'KING','Dad','Good Boys',2,'Poor');
INSERT INTO review_movies values(368,'WALKER','Spouse','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(369,'WHITE','Dad','IT Chapter two',3,'Average');
INSERT INTO review_movies values(370,'MARTINEZ','Spouse','Good Boys',3,'Average');
INSERT INTO review_movies values(371,'MARTIN','Spouse','Angel has fallen',3,'Average');
INSERT INTO review_movies values(372,'ADAMS','Friend','IT Chapter two',2,'Poor');
INSERT INTO review_movies values(373,'ELLIS','Friend','IT Chapter two',4,'Good');
INSERT INTO review_movies values(374,'GRIFFIN','Daughter','Ready or not',3,'Average');
INSERT INTO review_movies values(375,'TURNER','Daughter','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(376,'BROOKS','Friend','The lion king',3,'Average');
INSERT INTO review_movies values(377,'HARRIS','Son','Good Boys',2,'Poor');
INSERT INTO review_movies values(378,'GONZALEZ','Son','Ready or not',1,'Worst');
INSERT INTO review_movies values(379,'HAMILTON','Dad','Good Boys',5,'Excellent');
INSERT INTO review_movies values(380,'PALMER','Son','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(381,'FOSTER','Son','Good Boys',4,'Good');
INSERT INTO review_movies values(382,'BROOKS','Daughter','Ready or not',3,'Average');
INSERT INTO review_movies values(383,'COLE','Son','Good Boys',4,'Good');
INSERT INTO review_movies values(384,'MARTIN','Son','The lion king',3,'Average');
INSERT INTO review_movies values(385,'STEWART','Friend','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(386,'BRYANT','Daughter','The lion king',5,'Excellent');
INSERT INTO review_movies values(387,'KELLY','Friend','Angel has fallen',3,'Average');
INSERT INTO review_movies values(388,'FLORES','Friend','IT Chapter two',3,'Average');
INSERT INTO review_movies values(389,'BELL','Friend','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(390,'GIBSON','Spouse','IT Chapter two',4,'Good');
INSERT INTO review_movies values(391,'ROBINSON','Dad','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(392,'EVANS','Dad','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(393,'JAMES','Dad','Good Boys',5,'Excellent');
INSERT INTO review_movies values(394,'KENNEDY','Daughter','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(395,'ADAMS','Spouse','Angel has fallen',3,'Average');
INSERT INTO review_movies values(396,'ORTIZ','Dad','Good Boys',1,'Worst');
INSERT INTO review_movies values(397,'CARTER','Daughter','Ready or not',3,'Average');
INSERT INTO review_movies values(398,'CLARK','Dad','Ready or not',3,'Average');
INSERT INTO review_movies values(399,'WRIGHT','Spouse','Good Boys',2,'Poor');
INSERT INTO review_movies values(400,'OWENS','Friend','IT Chapter two',3,'Average');
INSERT INTO review_movies values(401,'MILLER','Spouse','The lion king',3,'Average');
INSERT INTO review_movies values(402,'GOMEZ','Son','IT Chapter two',2,'Poor');
INSERT INTO review_movies values(403,'WARD','Friend','Ready or not',3,'Average');
INSERT INTO review_movies values(404,'KING','Dad','Angel has fallen',3,'Average');
INSERT INTO review_movies values(405,'GREEN','Mom','Ready or not',5,'Excellent');
INSERT INTO review_movies values(406,'JOHNSON','Son','Ready or not',3,'Average');
INSERT INTO review_movies values(407,'MILLS','Mom','IT Chapter two',4,'Good');
INSERT INTO review_movies values(408,'KNIGHT','Dad','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(409,'CAMPBELL','Spouse','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(410,'SANCHEZ','Son','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(411,'GRANT','Friend','Good Boys',4,'Good');
INSERT INTO review_movies values(412,'WOODS','Friend','Ready or not',1,'Worst');
INSERT INTO review_movies values(413,'SIMMONS','Friend','The lion king',1,'Worst');
INSERT INTO review_movies values(414,'RICE','Daughter','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(415,'WALKER','Daughter','Good Boys',4,'Good');
INSERT INTO review_movies values(416,'WALKER','Dad','Ready or not',5,'Excellent');
INSERT INTO review_movies values(417,'GRAY','Spouse','The lion king',3,'Average');
INSERT INTO review_movies values(418,'JACKSON','Dad','Angel has fallen',4,'Good');
INSERT INTO review_movies values(419,'RODRIGUEZ','Daughter','Ready or not',2,'Poor');
INSERT INTO review_movies values(420,'GRAY','Dad','Good Boys',2,'Poor');
INSERT INTO review_movies values(421,'BROOKS','Spouse','Good Boys',2,'Poor');
INSERT INTO review_movies values(422,'DUNN','Mom','Ready or not',3,'Average');
INSERT INTO review_movies values(423,'MARSHALL','Son','IT Chapter two',4,'Good');
INSERT INTO review_movies values(424,'GRAY','Mom','Angel has fallen',3,'Average');
INSERT INTO review_movies values(425,'RICHARDSON','Daughter','IT Chapter two',2,'Poor');
INSERT INTO review_movies values(426,'MOORE','Mom','The lion king',2,'Poor');
INSERT INTO review_movies values(427,'EDWARDS','Mom','Good Boys',5,'Excellent');
INSERT INTO review_movies values(428,'STEWART','Son','Angel has fallen',4,'Good');
INSERT INTO review_movies values(429,'MURPHY','Dad','The lion king',3,'Average');
INSERT INTO review_movies values(430,'COLEMAN','Spouse','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(431,'TURNER','Dad','The lion king',2,'Poor');
INSERT INTO review_movies values(432,'RODRIGUEZ','Friend','Good Boys',5,'Excellent');
INSERT INTO review_movies values(433,'PATTERSON','Son','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(434,'DIXON','Spouse','Good Boys',5,'Excellent');
INSERT INTO review_movies values(435,'RICHARDSON','Dad','The lion king',1,'Worst');
INSERT INTO review_movies values(436,'STEVENS','Spouse','Ready or not',3,'Average');
INSERT INTO review_movies values(437,'WALLACE','Dad','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(438,'SMITH','Spouse','Ready or not',1,'Worst');
INSERT INTO review_movies values(439,'GRAHAM','Daughter','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(440,'BURNS','Son','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(441,'RODRIGUEZ','Spouse','The lion king',2,'Poor');
INSERT INTO review_movies values(442,'HAYES','Daughter','Ready or not',3,'Average');
INSERT INTO review_movies values(443,'GOMEZ','Spouse','Ready or not',3,'Average');
INSERT INTO review_movies values(444,'SHAW','Spouse','IT Chapter two',3,'Average');
INSERT INTO review_movies values(445,'HARRISON','Mom','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(446,'DANIELS','Mom','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(447,'WASHINGTON','Friend','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(448,'HUGHES','Friend','Ready or not',5,'Excellent');
INSERT INTO review_movies values(449,'GORDON','Dad','IT Chapter two',3,'Average');
INSERT INTO review_movies values(450,'FREEMAN','Spouse','Good Boys',5,'Excellent');
INSERT INTO review_movies values(451,'KENNEDY','Friend','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(452,'ROBINSON','Mom','IT Chapter two',4,'Good');
INSERT INTO review_movies values(453,'SIMMONS','Son','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(454,'PALMER','Daughter','Good Boys',4,'Good');
INSERT INTO review_movies values(455,'GONZALES','Son','Ready or not',4,'Good');
INSERT INTO review_movies values(456,'WASHINGTON','Mom','The lion king',1,'Worst');
INSERT INTO review_movies values(457,'BUTLER','Friend','Fast and Furious',3,'Average');
INSERT INTO review_movies values(458,'HILL','Son','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(459,'ROBINSON','Mom','Angel has fallen',3,'Average');
INSERT INTO review_movies values(460,'MORALES','Friend','The lion king',5,'Excellent');
INSERT INTO review_movies values(461,'TURNER','Spouse','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(462,'RAMOS','Mom','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(463,'PALMER','Friend','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(464,'BRYANT','Mom','IT Chapter two',2,'Poor');
INSERT INTO review_movies values(465,'GREEN','Dad','The lion king',1,'Worst');
INSERT INTO review_movies values(466,'WOODS','Mom','Fast and Furious',4,'Good');
INSERT INTO review_movies values(467,'DUNN','Friend','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(468,'TUCKER','Spouse','Ready or not',4,'Good');
INSERT INTO review_movies values(469,'PERRY','Dad','Ready or not',5,'Excellent');
INSERT INTO review_movies values(470,'HUNTER','Daughter','The lion king',2,'Poor');
INSERT INTO review_movies values(471,'CRUZ','Dad','IT Chapter two',4,'Good');
INSERT INTO review_movies values(472,'CRAWFORD','Dad','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(473,'OWENS','Spouse','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(474,'HUNT','Son','The lion king',5,'Excellent');
INSERT INTO review_movies values(475,'HUNTER','Mom','Good Boys',1,'Worst');
INSERT INTO review_movies values(476,'CARTER','Dad','IT Chapter two',4,'Good');
INSERT INTO review_movies values(477,'HICKS','Friend','Good Boys',2,'Poor');
INSERT INTO review_movies values(478,'STEVENS','Daughter','The lion king',2,'Poor');
INSERT INTO review_movies values(479,'WOODS','Mom','Good Boys',4,'Good');
INSERT INTO review_movies values(480,'MARTINEZ','Son','The lion king',4,'Good');
INSERT INTO review_movies values(481,'WALLACE','Daughter','The lion king',5,'Excellent');
INSERT INTO review_movies values(482,'KENNEDY','Dad','The lion king',1,'Worst');
INSERT INTO review_movies values(483,'HARRIS','Daughter','Good Boys',5,'Excellent');
INSERT INTO review_movies values(484,'FREEMAN','Son','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(485,'GRIFFIN','Spouse','Ready or not',3,'Average');
INSERT INTO review_movies values(486,'WOODS','Friend','IT Chapter two',3,'Average');
INSERT INTO review_movies values(487,'PALMER','Mom','Good Boys',5,'Excellent');
INSERT INTO review_movies values(488,'GONZALES','Friend','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(489,'WEST','Mom','Fast and Furious',3,'Average');
INSERT INTO review_movies values(490,'FORD','Daughter','Ready or not',1,'Worst');
INSERT INTO review_movies values(491,'STEWART','Son','Good Boys',4,'Good');
INSERT INTO review_movies values(492,'CAMPBELL','Son','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(493,'TUCKER','Friend','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(494,'REYES','Daughter','IT Chapter two',4,'Good');
INSERT INTO review_movies values(495,'WILSON','Dad','Fast and Furious',3,'Average');
INSERT INTO review_movies values(496,'HARRIS','Mom','Good Boys',5,'Excellent');
INSERT INTO review_movies values(497,'GONZALES','Son','Fast and Furious',4,'Good');
INSERT INTO review_movies values(498,'RAMOS','Daughter','Good Boys',1,'Worst');
INSERT INTO review_movies values(499,'BOYD','Dad','Good Boys',3,'Average');
INSERT INTO review_movies values(500,'SULLIVAN','Spouse','Angel has fallen',3,'Average');
INSERT INTO review_movies values(501,'MILLER','Mom','Angel has fallen',3,'Average');
INSERT INTO review_movies values(502,'WARD','Son','Good Boys',1,'Worst');
INSERT INTO review_movies values(503,'MILLS','Friend','The lion king',5,'Excellent');
INSERT INTO review_movies values(504,'RODRIGUEZ','Mom','Fast and Furious',3,'Average');
INSERT INTO review_movies values(505,'BUTLER','Friend','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(506,'ROBINSON','Dad','IT Chapter two',3,'Average');
INSERT INTO review_movies values(507,'BROWN','Daughter','Good Boys',1,'Worst');
INSERT INTO review_movies values(508,'FORD','Dad','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(509,'BUTLER','Mom','Ready or not',4,'Good');
INSERT INTO review_movies values(510,'STONE','Dad','The lion king',1,'Worst');
INSERT INTO review_movies values(511,'CLARK','Spouse','Fast and Furious',3,'Average');
INSERT INTO review_movies values(512,'JACKSON','Mom','Fast and Furious',4,'Good');
INSERT INTO review_movies values(513,'ROBERTS','Dad','Good Boys',3,'Average');
INSERT INTO review_movies values(514,'SHAW','Daughter','IT Chapter two',4,'Good');
INSERT INTO review_movies values(515,'BOYD','Friend','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(516,'MORALES','Mom','Ready or not',5,'Excellent');
INSERT INTO review_movies values(517,'JORDAN','Spouse','IT Chapter two',4,'Good');
INSERT INTO review_movies values(518,'DIXON','Daughter','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(519,'ELLIS','Dad','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(520,'ROBERTSON','Friend','Good Boys',2,'Poor');
INSERT INTO review_movies values(521,'ROGERS','Dad','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(522,'SULLIVAN','Spouse','Ready or not',4,'Good');
INSERT INTO review_movies values(523,'HAYES','Spouse','Ready or not',1,'Worst');
INSERT INTO review_movies values(524,'YOUNG','Mom','IT Chapter two',3,'Average');
INSERT INTO review_movies values(525,'HAYES','Dad','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(526,'WRIGHT','Daughter','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(527,'GRANT','Mom','IT Chapter two',4,'Good');
INSERT INTO review_movies values(528,'BENNETT','Daughter','Good Boys',5,'Excellent');
INSERT INTO review_movies values(529,'BLACK','Mom','IT Chapter two',4,'Good');
INSERT INTO review_movies values(530,'GONZALEZ','Daughter','Good Boys',2,'Poor');
INSERT INTO review_movies values(531,'LONG','Dad','The lion king',5,'Excellent');
INSERT INTO review_movies values(532,'MORALES','Mom','The lion king',5,'Excellent');
INSERT INTO review_movies values(533,'ROBINSON','Friend','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(534,'DAVIS','Dad','Good Boys',1,'Worst');
INSERT INTO review_movies values(535,'SCOTT','Dad','Ready or not',4,'Good');
INSERT INTO review_movies values(536,'HERNANDEZ','Friend','IT Chapter two',3,'Average');
INSERT INTO review_movies values(537,'COLE','Friend','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(538,'RAMIREZ','Mom','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(539,'ALLEN','Dad','Good Boys',1,'Worst');
INSERT INTO review_movies values(540,'HALL','Son','Good Boys',5,'Excellent');
INSERT INTO review_movies values(541,'SHAW','Spouse','Angel has fallen',4,'Good');
INSERT INTO review_movies values(542,'BELL','Son','Fast and Furious',4,'Good');
INSERT INTO review_movies values(543,'GRIFFIN','Son','IT Chapter two',4,'Good');
INSERT INTO review_movies values(544,'WOODS','Mom','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(545,'TORRES','Friend','The lion king',1,'Worst');
INSERT INTO review_movies values(546,'ORTIZ','Spouse','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(547,'BROOKS','Mom','The lion king',5,'Excellent');
INSERT INTO review_movies values(548,'PERRY','Daughter','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(549,'PRICE','Dad','Good Boys',1,'Worst');
INSERT INTO review_movies values(550,'FISHER','Friend','Ready or not',2,'Poor');
INSERT INTO review_movies values(551,'PRICE','Daughter','Good Boys',5,'Excellent');
INSERT INTO review_movies values(552,'ALLEN','Mom','The lion king',3,'Average');
INSERT INTO review_movies values(553,'JONES','Son','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(554,'THOMPSON','Daughter','Fast and Furious',4,'Good');
INSERT INTO review_movies values(555,'WARREN','Dad','Angel has fallen',4,'Good');
INSERT INTO review_movies values(556,'COLE','Mom','The lion king',5,'Excellent');
INSERT INTO review_movies values(557,'HARRISON','Dad','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(558,'FISHER','Dad','Good Boys',3,'Average');
INSERT INTO review_movies values(559,'TAYLOR','Friend','Ready or not',2,'Poor');
INSERT INTO review_movies values(560,'THOMPSON','Dad','Ready or not',2,'Poor');
INSERT INTO review_movies values(561,'REYNOLDS','Friend','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(562,'YOUNG','Friend','Good Boys',2,'Poor');
INSERT INTO review_movies values(563,'RICE','Daughter','Good Boys',1,'Worst');
INSERT INTO review_movies values(564,'GORDON','Daughter','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(565,'ELLIS','Spouse','The lion king',3,'Average');
INSERT INTO review_movies values(566,'KING','Spouse','Good Boys',2,'Poor');
INSERT INTO review_movies values(567,'DAVIS','Mom','Ready or not',1,'Worst');
INSERT INTO review_movies values(568,'RIVERA','Dad','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(569,'PRICE','Friend','The lion king',2,'Poor');
INSERT INTO review_movies values(570,'ROSS','Daughter','IT Chapter two',4,'Good');
INSERT INTO review_movies values(571,'PERRY','Spouse','Good Boys',3,'Average');
INSERT INTO review_movies values(572,'COOK','Dad','The lion king',5,'Excellent');
INSERT INTO review_movies values(573,'LEWIS','Mom','IT Chapter two',2,'Poor');
INSERT INTO review_movies values(574,'WILSON','Dad','Angel has fallen',3,'Average');
INSERT INTO review_movies values(575,'MARTINEZ','Spouse','Fast and Furious',3,'Average');
INSERT INTO review_movies values(576,'RIVERA','Friend','Good Boys',3,'Average');
INSERT INTO review_movies values(577,'SMITH','Daughter','Angel has fallen',4,'Good');
INSERT INTO review_movies values(578,'COLE','Friend','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(579,'NICHOLS','Mom','Good Boys',1,'Worst');
INSERT INTO review_movies values(580,'LEE','Son','IT Chapter two',3,'Average');
INSERT INTO review_movies values(581,'REYNOLDS','Dad','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(582,'BRYANT','Friend','Good Boys',1,'Worst');
INSERT INTO review_movies values(583,'MILLER','Spouse','Ready or not',4,'Good');
INSERT INTO review_movies values(584,'COOK','Mom','Ready or not',2,'Poor');
INSERT INTO review_movies values(585,'OWENS','Daughter','Ready or not',4,'Good');
INSERT INTO review_movies values(586,'MITCHELL','Friend','IT Chapter two',4,'Good');
INSERT INTO review_movies values(587,'BENNETT','Dad','Fast and Furious',4,'Good');
INSERT INTO review_movies values(588,'CRUZ','Friend','Fast and Furious',3,'Average');
INSERT INTO review_movies values(589,'HAYES','Mom','The lion king',2,'Poor');
INSERT INTO review_movies values(590,'PATTERSON','Spouse','Good Boys',1,'Worst');
INSERT INTO review_movies values(591,'REYNOLDS','Dad','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(592,'SIMMONS','Spouse','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(593,'STONE','Friend','IT Chapter two',2,'Poor');
INSERT INTO review_movies values(594,'PORTER','Daughter','The lion king',5,'Excellent');
INSERT INTO review_movies values(595,'CAMPBELL','Mom','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(596,'KNIGHT','Spouse','Ready or not',2,'Poor');
INSERT INTO review_movies values(597,'GRIFFIN','Son','Angel has fallen',4,'Good');
INSERT INTO review_movies values(598,'CARTER','Son','The lion king',1,'Worst');
INSERT INTO review_movies values(599,'RIVERA','Son','The lion king',3,'Average');
INSERT INTO review_movies values(600,'EDWARDS','Daughter','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(601,'KNIGHT','Spouse','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(602,'WILLIAMS','Son','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(603,'ROSE','Friend','Ready or not',4,'Good');
INSERT INTO review_movies values(604,'RICHARDSON','Daughter','Ready or not',4,'Good');
INSERT INTO review_movies values(605,'MORRIS','Mom','Fast and Furious',4,'Good');
INSERT INTO review_movies values(606,'HOLMES','Dad','Fast and Furious',4,'Good');
INSERT INTO review_movies values(607,'RAMIREZ','Friend','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(608,'MARSHALL','Spouse','IT Chapter two',2,'Poor');
INSERT INTO review_movies values(609,'KENNEDY','Mom','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(610,'GOMEZ','Mom','Good Boys',5,'Excellent');
INSERT INTO review_movies values(611,'LEE','Mom','Ready or not',1,'Worst');
INSERT INTO review_movies values(612,'WALKER','Spouse','IT Chapter two',3,'Average');
INSERT INTO review_movies values(613,'HICKS','Friend','Good Boys',4,'Good');
INSERT INTO review_movies values(614,'JAMES','Son','IT Chapter two',4,'Good');
INSERT INTO review_movies values(615,'COLE','Son','Ready or not',5,'Excellent');
INSERT INTO review_movies values(616,'WRIGHT','Mom','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(617,'STONE','Daughter','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(618,'DANIELS','Son','Ready or not',2,'Poor');
INSERT INTO review_movies values(619,'ROBERTSON','Mom','The lion king',4,'Good');
INSERT INTO review_movies values(620,'TUCKER','Daughter','Ready or not',1,'Worst');
INSERT INTO review_movies values(621,'JOHNSON','Spouse','Good Boys',2,'Poor');
INSERT INTO review_movies values(622,'BARNES','Mom','Ready or not',4,'Good');
INSERT INTO review_movies values(623,'EDWARDS','Daughter','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(624,'RODRIGUEZ','Friend','Good Boys',3,'Average');
INSERT INTO review_movies values(625,'GIBSON','Mom','Fast and Furious',3,'Average');
INSERT INTO review_movies values(626,'ADAMS','Friend','Angel has fallen',3,'Average');
INSERT INTO review_movies values(627,'THOMPSON','Son','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(628,'MURPHY','Spouse','Good Boys',4,'Good');
INSERT INTO review_movies values(629,'COOK','Son','Fast and Furious',4,'Good');
INSERT INTO review_movies values(630,'BROWN','Dad','Good Boys',1,'Worst');
INSERT INTO review_movies values(631,'MORALES','Friend','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(632,'RAMOS','Mom','The lion king',4,'Good');
INSERT INTO review_movies values(633,'MURRAY','Spouse','Ready or not',1,'Worst');
INSERT INTO review_movies values(634,'CAMPBELL','Son','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(635,'MURRAY','Friend','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(636,'MILLER','Friend','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(637,'COLLINS','Spouse','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(638,'COLEMAN','Son','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(639,'MORALES','Son','Ready or not',5,'Excellent');
INSERT INTO review_movies values(640,'JOHNSON','Spouse','Fast and Furious',3,'Average');
INSERT INTO review_movies values(641,'PARKER','Daughter','IT Chapter two',3,'Average');
INSERT INTO review_movies values(642,'KENNEDY','Dad','Good Boys',2,'Poor');
INSERT INTO review_movies values(643,'MARSHALL','Dad','The lion king',2,'Poor');
INSERT INTO review_movies values(644,'MASON','Daughter','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(645,'PORTER','Son','Fast and Furious',3,'Average');
INSERT INTO review_movies values(646,'HOWARD','Friend','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(647,'WARREN','Daughter','Angel has fallen',3,'Average');
INSERT INTO review_movies values(648,'HAWKINS','Son','IT Chapter two',3,'Average');
INSERT INTO review_movies values(649,'REYES','Mom','Ready or not',2,'Poor');
INSERT INTO review_movies values(650,'GRANT','Son','The lion king',1,'Worst');
INSERT INTO review_movies values(651,'WRIGHT','Dad','The lion king',4,'Good');
INSERT INTO review_movies values(652,'MYERS','Son','Ready or not',2,'Poor');
INSERT INTO review_movies values(653,'BARNES','Dad','Good Boys',4,'Good');
INSERT INTO review_movies values(654,'HAYES','Spouse','Fast and Furious',3,'Average');
INSERT INTO review_movies values(655,'SANDERS','Daughter','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(656,'BELL','Daughter','The lion king',3,'Average');
INSERT INTO review_movies values(657,'GRAY','Spouse','Angel has fallen',4,'Good');
INSERT INTO review_movies values(658,'GRIFFIN','Spouse','IT Chapter two',4,'Good');
INSERT INTO review_movies values(659,'FISHER','Friend','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(660,'THOMAS','Son','Good Boys',5,'Excellent');
INSERT INTO review_movies values(661,'JORDAN','Dad','The lion king',3,'Average');
INSERT INTO review_movies values(662,'KING','Mom','Ready or not',1,'Worst');
INSERT INTO review_movies values(663,'SANCHEZ','Mom','Fast and Furious',4,'Good');
INSERT INTO review_movies values(664,'MORALES','Daughter','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(665,'ROGERS','Spouse','Fast and Furious',3,'Average');
INSERT INTO review_movies values(666,'MCDONALD','Friend','IT Chapter two',4,'Good');
INSERT INTO review_movies values(667,'MITCHELL','Dad','Good Boys',1,'Worst');
INSERT INTO review_movies values(668,'EVANS','Son','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(669,'YOUNG','Daughter','The lion king',2,'Poor');
INSERT INTO review_movies values(670,'PHILLIPS','Mom','Good Boys',3,'Average');
INSERT INTO review_movies values(671,'HARRISON','Friend','The lion king',4,'Good');
INSERT INTO review_movies values(672,'MURPHY','Spouse','Angel has fallen',3,'Average');
INSERT INTO review_movies values(673,'LEE','Daughter','The lion king',5,'Excellent');
INSERT INTO review_movies values(674,'COOK','Dad','IT Chapter two',2,'Poor');
INSERT INTO review_movies values(675,'SMITH','Daughter','Fast and Furious',4,'Good');
INSERT INTO review_movies values(676,'FREEMAN','Daughter','Ready or not',4,'Good');
INSERT INTO review_movies values(677,'HENDERSON','Spouse','Ready or not',5,'Excellent');
INSERT INTO review_movies values(678,'STEVENS','Mom','Good Boys',2,'Poor');
INSERT INTO review_movies values(679,'DAVIS','Mom','The lion king',5,'Excellent');
INSERT INTO review_movies values(680,'WARREN','Spouse','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(681,'JONES','Spouse','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(682,'BENNETT','Son','Ready or not',4,'Good');
INSERT INTO review_movies values(683,'ROBERTSON','Dad','Good Boys',2,'Poor');
INSERT INTO review_movies values(684,'SULLIVAN','Spouse','Fast and Furious',4,'Good');
INSERT INTO review_movies values(685,'REYES','Daughter','IT Chapter two',3,'Average');
INSERT INTO review_movies values(686,'NICHOLS','Son','Good Boys',1,'Worst');
INSERT INTO review_movies values(687,'HOWARD','Son','The lion king',4,'Good');
INSERT INTO review_movies values(688,'HOLMES','Dad','Good Boys',3,'Average');
INSERT INTO review_movies values(689,'KENNEDY','Son','Ready or not',3,'Average');
INSERT INTO review_movies values(690,'GRIFFIN','Friend','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(691,'LEE','Spouse','The lion king',1,'Worst');
INSERT INTO review_movies values(692,'HAMILTON','Friend','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(693,'PHILLIPS','Dad','The lion king',5,'Excellent');
INSERT INTO review_movies values(694,'THOMAS','Dad','The lion king',1,'Worst');
INSERT INTO review_movies values(695,'PRICE','Daughter','Ready or not',4,'Good');
INSERT INTO review_movies values(696,'YOUNG','Mom','Good Boys',4,'Good');
INSERT INTO review_movies values(697,'KENNEDY','Spouse','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(698,'COLE','Daughter','Good Boys',1,'Worst');
INSERT INTO review_movies values(699,'WELLS','Son','Fast and Furious',4,'Good');
INSERT INTO review_movies values(700,'RAMOS','Son','Angel has fallen',3,'Average');
INSERT INTO review_movies values(701,'ALLEN','Spouse','Good Boys',5,'Excellent');
INSERT INTO review_movies values(702,'COOPER','Son','Ready or not',1,'Worst');
INSERT INTO review_movies values(703,'FORD','Mom','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(704,'FOSTER','Mom','Good Boys',5,'Excellent');
INSERT INTO review_movies values(705,'WARD','Friend','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(706,'HUNT','Son','Ready or not',5,'Excellent');
INSERT INTO review_movies values(707,'DANIELS','Dad','The lion king',2,'Poor');
INSERT INTO review_movies values(708,'WALKER','Mom','Good Boys',3,'Average');
INSERT INTO review_movies values(709,'HUGHES','Friend','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(710,'RAMIREZ','Son','Fast and Furious',3,'Average');
INSERT INTO review_movies values(711,'SIMPSON','Spouse','The lion king',5,'Excellent');
INSERT INTO review_movies values(712,'CLARK','Friend','IT Chapter two',3,'Average');
INSERT INTO review_movies values(713,'WALLACE','Spouse','The lion king',1,'Worst');
INSERT INTO review_movies values(714,'WEST','Friend','Fast and Furious',3,'Average');
INSERT INTO review_movies values(715,'HERNANDEZ','Son','Ready or not',4,'Good');
INSERT INTO review_movies values(716,'PRICE','Son','Ready or not',4,'Good');
INSERT INTO review_movies values(717,'PATTERSON','Dad','Angel has fallen',4,'Good');
INSERT INTO review_movies values(718,'MURPHY','Mom','Good Boys',3,'Average');
INSERT INTO review_movies values(719,'KING','Mom','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(720,'MARTINEZ','Friend','The lion king',5,'Excellent');
INSERT INTO review_movies values(721,'LEE','Son','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(722,'SULLIVAN','Dad','Fast and Furious',4,'Good');
INSERT INTO review_movies values(723,'DIAZ','Friend','Fast and Furious',3,'Average');
INSERT INTO review_movies values(724,'WILSON','Son','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(725,'YOUNG','Spouse','Good Boys',3,'Average');
INSERT INTO review_movies values(726,'ADAMS','Mom','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(727,'DIAZ','Friend','The lion king',4,'Good');
INSERT INTO review_movies values(728,'RICE','Friend','The lion king',2,'Poor');
INSERT INTO review_movies values(729,'ROBERTS','Daughter','Ready or not',2,'Poor');
INSERT INTO review_movies values(730,'FORD','Mom','The lion king',5,'Excellent');
INSERT INTO review_movies values(731,'BUTLER','Mom','The lion king',1,'Worst');
INSERT INTO review_movies values(732,'STONE','Friend','Fast and Furious',3,'Average');
INSERT INTO review_movies values(733,'GARCIA','Daughter','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(734,'MORGAN','Son','Fast and Furious',4,'Good');
INSERT INTO review_movies values(735,'HUNTER','Daughter','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(736,'YOUNG','Dad','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(737,'SANCHEZ','Friend','Good Boys',4,'Good');
INSERT INTO review_movies values(738,'SCOTT','Dad','IT Chapter two',4,'Good');
INSERT INTO review_movies values(739,'DAVIS','Friend','Ready or not',2,'Poor');
INSERT INTO review_movies values(740,'MARTINEZ','Mom','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(741,'WEBB','Spouse','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(742,'RUSSELL','Son','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(743,'COX','Son','The lion king',3,'Average');
INSERT INTO review_movies values(744,'CARTER','Friend','The lion king',5,'Excellent');
INSERT INTO review_movies values(745,'JACKSON','Mom','The lion king',3,'Average');
INSERT INTO review_movies values(746,'FREEMAN','Daughter','Ready or not',4,'Good');
INSERT INTO review_movies values(747,'ALLEN','Friend','Good Boys',4,'Good');
INSERT INTO review_movies values(748,'PORTER','Spouse','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(749,'ADAMS','Spouse','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(750,'YOUNG','Dad','The lion king',5,'Excellent');
INSERT INTO review_movies values(751,'JORDAN','Spouse','The lion king',2,'Poor');
INSERT INTO review_movies values(752,'FORD','Mom','The lion king',1,'Worst');
INSERT INTO review_movies values(753,'BRYANT','Dad','Good Boys',2,'Poor');
INSERT INTO review_movies values(754,'COLE','Dad','IT Chapter two',4,'Good');
INSERT INTO review_movies values(755,'JACKSON','Spouse','Ready or not',2,'Poor');
INSERT INTO review_movies values(756,'MORRIS','Dad','Ready or not',2,'Poor');
INSERT INTO review_movies values(757,'HENDERSON','Dad','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(758,'JONES','Friend','Ready or not',4,'Good');
INSERT INTO review_movies values(759,'OWENS','Dad','The lion king',5,'Excellent');
INSERT INTO review_movies values(760,'HAYES','Son','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(761,'GOMEZ','Son','Ready or not',4,'Good');
INSERT INTO review_movies values(762,'DANIELS','Dad','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(763,'JACKSON','Daughter','The lion king',4,'Good');
INSERT INTO review_movies values(764,'ORTIZ','Friend','Good Boys',3,'Average');
INSERT INTO review_movies values(765,'GRAHAM','Friend','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(766,'FOSTER','Spouse','IT Chapter two',2,'Poor');
INSERT INTO review_movies values(767,'MASON','Mom','Ready or not',1,'Worst');
INSERT INTO review_movies values(768,'MILLS','Friend','Ready or not',3,'Average');
INSERT INTO review_movies values(769,'JAMES','Dad','The lion king',3,'Average');
INSERT INTO review_movies values(770,'KNIGHT','Mom','Ready or not',3,'Average');
INSERT INTO review_movies values(771,'MORRIS','Friend','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(772,'THOMAS','Daughter','Fast and Furious',4,'Good');
INSERT INTO review_movies values(773,'STONE','Daughter','Angel has fallen',3,'Average');
INSERT INTO review_movies values(774,'COLEMAN','Daughter','Good Boys',3,'Average');
INSERT INTO review_movies values(775,'NELSON','Son','The lion king',1,'Worst');
INSERT INTO review_movies values(776,'DANIELS','Spouse','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(777,'BAILEY','Mom','Fast and Furious',3,'Average');
INSERT INTO review_movies values(778,'RAMIREZ','Spouse','Angel has fallen',3,'Average');
INSERT INTO review_movies values(779,'ROSS','Spouse','Good Boys',3,'Average');
INSERT INTO review_movies values(780,'LEWIS','Daughter','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(781,'GRAY','Dad','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(782,'ROSE','Daughter','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(783,'MORRIS','Dad','Ready or not',1,'Worst');
INSERT INTO review_movies values(784,'DIAZ','Friend','Good Boys',5,'Excellent');
INSERT INTO review_movies values(785,'RAMIREZ','Friend','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(786,'KENNEDY','Daughter','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(787,'FLORES','Friend','Ready or not',1,'Worst');
INSERT INTO review_movies values(788,'WRIGHT','Dad','The lion king',2,'Poor');
INSERT INTO review_movies values(789,'WILLIAMS','Spouse','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(790,'MORGAN','Mom','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(791,'PHILLIPS','Friend','The lion king',1,'Worst');
INSERT INTO review_movies values(792,'PORTER','Mom','Ready or not',2,'Poor');
INSERT INTO review_movies values(793,'POWELL','Dad','IT Chapter two',3,'Average');
INSERT INTO review_movies values(794,'SMITH','Son','Ready or not',1,'Worst');
INSERT INTO review_movies values(795,'PERRY','Friend','Good Boys',1,'Worst');
INSERT INTO review_movies values(796,'JENKINS','Spouse','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(797,'WILSON','Dad','Ready or not',2,'Poor');
INSERT INTO review_movies values(798,'FLORES','Spouse','The lion king',2,'Poor');
INSERT INTO review_movies values(799,'SANCHEZ','Dad','Fast and Furious',4,'Good');
INSERT INTO review_movies values(800,'ROBERTSON','Spouse','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(801,'GRIFFIN','Friend','Angel has fallen',3,'Average');
INSERT INTO review_movies values(802,'MARSHALL','Daughter','The lion king',2,'Poor');
INSERT INTO review_movies values(803,'TURNER','Mom','Ready or not',3,'Average');
INSERT INTO review_movies values(804,'JAMES','Spouse','Angel has fallen',3,'Average');
INSERT INTO review_movies values(805,'FERGUSON','Mom','IT Chapter two',2,'Poor');
INSERT INTO review_movies values(806,'HAWKINS','Friend','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(807,'BENNETT','Spouse','Fast and Furious',3,'Average');
INSERT INTO review_movies values(808,'CLARK','Son','Ready or not',2,'Poor');
INSERT INTO review_movies values(809,'ROBERTSON','Daughter','Ready or not',4,'Good');
INSERT INTO review_movies values(810,'PEREZ','Mom','Good Boys',2,'Poor');
INSERT INTO review_movies values(811,'PRICE','Mom','The lion king',4,'Good');
INSERT INTO review_movies values(812,'JOHNSON','Dad','Ready or not',2,'Poor');
INSERT INTO review_movies values(813,'THOMAS','Friend','Fast and Furious',4,'Good');
INSERT INTO review_movies values(814,'THOMPSON','Mom','Ready or not',3,'Average');
INSERT INTO review_movies values(815,'PALMER','Son','Good Boys',4,'Good');
INSERT INTO review_movies values(816,'COLEMAN','Friend','Ready or not',2,'Poor');
INSERT INTO review_movies values(817,'BLACK','Daughter','Ready or not',1,'Worst');
INSERT INTO review_movies values(818,'EVANS','Dad','Ready or not',5,'Excellent');
INSERT INTO review_movies values(819,'TAYLOR','Spouse','Fast and Furious',3,'Average');
INSERT INTO review_movies values(820,'ELLIS','Spouse','Ready or not',5,'Excellent');
INSERT INTO review_movies values(821,'HOLMES','Dad','The lion king',5,'Excellent');
INSERT INTO review_movies values(822,'HILL','Daughter','Ready or not',2,'Poor');
INSERT INTO review_movies values(823,'COOK','Friend','Angel has fallen',4,'Good');
INSERT INTO review_movies values(824,'EVANS','Daughter','Ready or not',4,'Good');
INSERT INTO review_movies values(825,'OWENS','Spouse','The lion king',2,'Poor');
INSERT INTO review_movies values(826,'HILL','Daughter','IT Chapter two',4,'Good');
INSERT INTO review_movies values(827,'SULLIVAN','Daughter','Angel has fallen',3,'Average');
INSERT INTO review_movies values(828,'WELLS','Spouse','Angel has fallen',4,'Good');
INSERT INTO review_movies values(829,'STEVENS','Daughter','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(830,'ROBERTSON','Daughter','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(831,'MILLS','Mom','Angel has fallen',4,'Good');
INSERT INTO review_movies values(832,'POWELL','Son','Angel has fallen',3,'Average');
INSERT INTO review_movies values(833,'SHAW','Friend','Good Boys',1,'Worst');
INSERT INTO review_movies values(834,'WATSON','Mom','Angel has fallen',4,'Good');
INSERT INTO review_movies values(835,'MITCHELL','Daughter','The lion king',4,'Good');
INSERT INTO review_movies values(836,'CAMPBELL','Friend','The lion king',1,'Worst');
INSERT INTO review_movies values(837,'HAYES','Son','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(838,'WALKER','Daughter','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(839,'WOODS','Son','Ready or not',2,'Poor');
INSERT INTO review_movies values(840,'GRAY','Dad','Good Boys',5,'Excellent');
INSERT INTO review_movies values(841,'BRYANT','Daughter','Fast and Furious',3,'Average');
INSERT INTO review_movies values(842,'GRIFFIN','Mom','IT Chapter two',3,'Average');
INSERT INTO review_movies values(843,'WARD','Son','Good Boys',4,'Good');
INSERT INTO review_movies values(844,'BARNES','Son','Good Boys',4,'Good');
INSERT INTO review_movies values(845,'MITCHELL','Mom','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(846,'JOHNSON','Friend','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(847,'CRUZ','Mom','Ready or not',3,'Average');
INSERT INTO review_movies values(848,'MARSHALL','Friend','IT Chapter two',3,'Average');
INSERT INTO review_movies values(849,'BENNETT','Dad','Angel has fallen',3,'Average');
INSERT INTO review_movies values(850,'CRAWFORD','Son','Ready or not',2,'Poor');
INSERT INTO review_movies values(851,'BUTLER','Mom','The lion king',3,'Average');
INSERT INTO review_movies values(852,'PHILLIPS','Spouse','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(853,'LEWIS','Daughter','Good Boys',1,'Worst');
INSERT INTO review_movies values(854,'RAMIREZ','Spouse','Ready or not',5,'Excellent');
INSERT INTO review_movies values(855,'CARTER','Spouse','Good Boys',1,'Worst');
INSERT INTO review_movies values(856,'ROGERS','Daughter','Angel has fallen',4,'Good');
INSERT INTO review_movies values(857,'JAMES','Friend','The lion king',5,'Excellent');
INSERT INTO review_movies values(858,'GREEN','Daughter','The lion king',1,'Worst');
INSERT INTO review_movies values(859,'GOMEZ','Mom','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(860,'MORGAN','Mom','Good Boys',4,'Good');
INSERT INTO review_movies values(861,'COLLINS','Dad','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(862,'TORRES','Daughter','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(863,'BRYANT','Friend','Ready or not',3,'Average');
INSERT INTO review_movies values(864,'BRYANT','Daughter','Ready or not',2,'Poor');
INSERT INTO review_movies values(865,'REED','Friend','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(866,'JONES','Mom','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(867,'NICHOLS','Dad','The lion king',5,'Excellent');
INSERT INTO review_movies values(868,'MARTIN','Son','Fast and Furious',4,'Good');
INSERT INTO review_movies values(869,'BURNS','Son','Ready or not',1,'Worst');
INSERT INTO review_movies values(870,'SULLIVAN','Mom','Good Boys',2,'Poor');
INSERT INTO review_movies values(871,'EDWARDS','Daughter','Good Boys',5,'Excellent');
INSERT INTO review_movies values(872,'HENDERSON','Son','IT Chapter two',3,'Average');
INSERT INTO review_movies values(873,'HAWKINS','Spouse','Angel has fallen',4,'Good');
INSERT INTO review_movies values(874,'ADAMS','Son','Ready or not',3,'Average');
INSERT INTO review_movies values(875,'PRICE','Mom','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(876,'OWENS','Daughter','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(877,'MURRAY','Friend','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(878,'ROBERTS','Dad','Ready or not',5,'Excellent');
INSERT INTO review_movies values(879,'BROWN','Mom','Fast and Furious',4,'Good');
INSERT INTO review_movies values(880,'PALMER','Mom','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(881,'RUSSELL','Friend','Ready or not',5,'Excellent');
INSERT INTO review_movies values(882,'HUNT','Daughter','The lion king',3,'Average');
INSERT INTO review_movies values(883,'STONE','Mom','The lion king',1,'Worst');
INSERT INTO review_movies values(884,'REYES','Daughter','IT Chapter two',2,'Poor');
INSERT INTO review_movies values(885,'BELL','Friend','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(886,'CRUZ','Dad','The lion king',2,'Poor');
INSERT INTO review_movies values(887,'MARTIN','Mom','Angel has fallen',3,'Average');
INSERT INTO review_movies values(888,'MCDONALD','Dad','Angel has fallen',4,'Good');
INSERT INTO review_movies values(889,'ALEXANDER','Dad','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(890,'KNIGHT','Dad','The lion king',1,'Worst');
INSERT INTO review_movies values(891,'JONES','Dad','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(892,'JONES','Son','Ready or not',2,'Poor');
INSERT INTO review_movies values(893,'COLLINS','Son','Good Boys',1,'Worst');
INSERT INTO review_movies values(894,'GRIFFIN','Son','Ready or not',3,'Average');
INSERT INTO review_movies values(895,'SIMPSON','Son','Ready or not',4,'Good');
INSERT INTO review_movies values(896,'BAILEY','Mom','The lion king',2,'Poor');
INSERT INTO review_movies values(897,'HARRIS','Son','Fast and Furious',3,'Average');
INSERT INTO review_movies values(898,'CRUZ','Daughter','Angel has fallen',4,'Good');
INSERT INTO review_movies values(899,'COLEMAN','Dad','The lion king',3,'Average');
INSERT INTO review_movies values(900,'HOWARD','Dad','The lion king',2,'Poor');
INSERT INTO review_movies values(901,'GREEN','Son','Good Boys',2,'Poor');
INSERT INTO review_movies values(902,'GONZALEZ','Spouse','IT Chapter two',4,'Good');
INSERT INTO review_movies values(903,'CAMPBELL','Daughter','Good Boys',2,'Poor');
INSERT INTO review_movies values(904,'JACKSON','Spouse','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(905,'YOUNG','Friend','IT Chapter two',3,'Average');
INSERT INTO review_movies values(906,'HUNTER','Friend','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(907,'WRIGHT','Son','Good Boys',4,'Good');
INSERT INTO review_movies values(908,'ROSE','Mom','IT Chapter two',4,'Good');
INSERT INTO review_movies values(909,'MARTINEZ','Friend','Fast and Furious',3,'Average');
INSERT INTO review_movies values(910,'SMITH','Friend','Fast and Furious',4,'Good');
INSERT INTO review_movies values(911,'WALLACE','Mom','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(912,'CRAWFORD','Spouse','The lion king',5,'Excellent');
INSERT INTO review_movies values(913,'LEWIS','Daughter','Ready or not',4,'Good');
INSERT INTO review_movies values(914,'COOK','Dad','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(915,'PEREZ','Son','Good Boys',1,'Worst');
INSERT INTO review_movies values(916,'RODRIGUEZ','Spouse','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(917,'BUTLER','Dad','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(918,'WALKER','Son','Fast and Furious',3,'Average');
INSERT INTO review_movies values(919,'SULLIVAN','Spouse','Good Boys',3,'Average');
INSERT INTO review_movies values(920,'THOMAS','Daughter','The lion king',1,'Worst');
INSERT INTO review_movies values(921,'MOORE','Daughter','Ready or not',5,'Excellent');
INSERT INTO review_movies values(922,'SIMMONS','Mom','Good Boys',3,'Average');
INSERT INTO review_movies values(923,'LEWIS','Son','Angel has fallen',4,'Good');
INSERT INTO review_movies values(924,'HUNT','Mom','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(925,'MORALES','Friend','Good Boys',3,'Average');
INSERT INTO review_movies values(926,'NELSON','Daughter','The lion king',1,'Worst');
INSERT INTO review_movies values(927,'BROOKS','Friend','Good Boys',3,'Average');
INSERT INTO review_movies values(928,'MITCHELL','Dad','Ready or not',1,'Worst');
INSERT INTO review_movies values(929,'ROBINSON','Dad','Angel has fallen',4,'Good');
INSERT INTO review_movies values(930,'GRAHAM','Spouse','The lion king',3,'Average');
INSERT INTO review_movies values(931,'HAMILTON','Friend','Fast and Furious',2,'Poor');
INSERT INTO review_movies values(932,'MITCHELL','Son','Angel has fallen',4,'Good');
INSERT INTO review_movies values(933,'COLLINS','Mom','The lion king',4,'Good');
INSERT INTO review_movies values(934,'GRAHAM','Son','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(935,'COLLINS','Spouse','The lion king',3,'Average');
INSERT INTO review_movies values(936,'DIAZ','Spouse','The lion king',4,'Good');
INSERT INTO review_movies values(937,'SIMPSON','Dad','The lion king',3,'Average');
INSERT INTO review_movies values(938,'NICHOLS','Dad','Fast and Furious',4,'Good');
INSERT INTO review_movies values(939,'THOMAS','Daughter','Good Boys',5,'Excellent');
INSERT INTO review_movies values(940,'SANDERS','Daughter','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(941,'PERRY','Dad','Angel has fallen',3,'Average');
INSERT INTO review_movies values(942,'KELLY','Mom','Good Boys',2,'Poor');
INSERT INTO review_movies values(943,'HALL','Dad','The lion king',4,'Good');
INSERT INTO review_movies values(944,'RODRIGUEZ','Friend','Good Boys',5,'Excellent');
INSERT INTO review_movies values(945,'DIXON','Dad','Fast and Furious',5,'Excellent');
INSERT INTO review_movies values(946,'REYES','Spouse','Good Boys',3,'Average');
INSERT INTO review_movies values(947,'MOORE','Mom','IT Chapter two',1,'Worst');
INSERT INTO review_movies values(948,'PALMER','Mom','Ready or not',4,'Good');
INSERT INTO review_movies values(949,'DIXON','Dad','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(950,'PERRY','Son','Angel has fallen',5,'Excellent');
INSERT INTO review_movies values(951,'PETERSON','Son','IT Chapter two',4,'Good');
INSERT INTO review_movies values(952,'RICE','Dad','Good Boys',3,'Average');
INSERT INTO review_movies values(953,'NELSON','Son','Ready or not',2,'');
INSERT INTO review_movies values(954,'GIBSON','Son','Good Boys',4,'');
INSERT INTO review_movies values(955,'ROGERS','Son','The lion king',4,'');
INSERT INTO review_movies values(956,'MCDONALD','Friend','Angel has fallen',2,'');
INSERT INTO review_movies values(957,'CRUZ','Son','Good Boys',4,'');
INSERT INTO review_movies values(958,'MITCHELL','Friend','Good Boys',1,'Worst');
INSERT INTO review_movies values(959,'GONZALES','Mom','The lion king',2,'Poor');
INSERT INTO review_movies values(960,'HENDERSON','Mom','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(961,'HOLMES','Daughter','The lion king',3,'Average');
INSERT INTO review_movies values(962,'ROSS','Dad','Good Boys',3,'Average');
INSERT INTO review_movies values(963,'TORRES','Friend','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(964,'SANDERS','Daughter','The lion king',5,'Excellent');
INSERT INTO review_movies values(965,'ROGERS','Daughter','The lion king',2,'Poor');
INSERT INTO review_movies values(966,'NELSON','Friend','The lion king',4,'Good');
INSERT INTO review_movies values(967,'ORTIZ','Friend','Fast and Furious',1,'Worst');
INSERT INTO review_movies values(968,'PERRY','Dad','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(969,'WEST','Mom','IT Chapter two',2,'Poor');
INSERT INTO review_movies values(970,'HENDERSON','Friend','Angel has fallen',4,'Good');
INSERT INTO review_movies values(971,'FLORES','Daughter','The lion king',2,'Poor');
INSERT INTO review_movies values(972,'ORTIZ','Son','Good Boys',4,'Good');
INSERT INTO review_movies values(973,'RUSSELL','Son','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(974,'ANDERSON','Spouse','Ready or not',1,'Worst');
INSERT INTO review_movies values(975,'MCDONALD','Mom','Ready or not',2,'Poor');
INSERT INTO review_movies values(976,'PETERSON','Daughter','Angel has fallen',1,'Worst');
INSERT INTO review_movies values(977,'RODRIGUEZ','Daughter','Good Boys',1,'Worst');
INSERT INTO review_movies values(978,'WEBB','Dad','The lion king',5,'Excellent');
INSERT INTO review_movies values(979,'HUNTER','Son','Good Boys',3,'Average');
INSERT INTO review_movies values(980,'HARRISON','Daughter','The lion king',4,'Good');
INSERT INTO review_movies values(981,'GONZALES','Mom','Good Boys',2,'Poor');
INSERT INTO review_movies values(982,'KENNEDY','Mom','Angel has fallen',2,'Poor');
INSERT INTO review_movies values(983,'GREEN','Son','IT Chapter two',5,'Excellent');
INSERT INTO review_movies values(984,'KELLY','Son','Ready or not',5,'Excellent');
INSERT INTO review_movies values(985,'ORTIZ','Daughter','Ready or not',1,'Worst');
INSERT INTO review_movies values(986,'OWENS','Daughter','Fast and Furious',4,'Good');
INSERT INTO review_movies values(987,'JONES','Mom','Angel has fallen',3,'');
INSERT INTO review_movies values(988,'HERNANDEZ','Dad','Ready or not',5,'');
INSERT INTO review_movies values(989,'WRIGHT','Friend','IT Chapter two',3,'');
INSERT INTO review_movies values(990,'MURRAY','Son','IT Chapter two',2,'');
INSERT INTO review_movies values(991,'ALEXANDER','Dad','Fast and Furious',1,'');
INSERT INTO review_movies values(992,'FERGUSON','Spouse','Fast and Furious',4,'');
INSERT INTO review_movies values(993,'ROGERS','Son','Angel has fallen',3,'');
INSERT INTO review_movies values(994,'HUNT','Daughter','The lion king',1,'');
INSERT INTO review_movies values(995,'GIBSON','Friend','Fast and Furious',3,'');
INSERT INTO review_movies values(996,'LOPEZ','Mom','IT Chapter two',4,'');
INSERT INTO review_movies values(997,'WARD','Daughter','Fast and Furious',5,'');
INSERT INTO review_movies values(998,'MITCHELL','Daughter','Ready or not',4,'');
INSERT INTO review_movies values(999,'HUGHES','Son','Good Boys',3,'Average');
INSERT INTO review_movies values(1000,'DANIELS','Dad','Good Boys',2,'Poor');

