---
title: "607_Week5_Assignment_Jeyaraman_Ramalingam"
author: "Jeyaraman Ramalingam"
date: "9/29/2019"
output: html_document
---

```{r setup, eval=TRUE}
library(bitops)
library(plyr)
library(RCurl)
library(dplyr)
library(tidyr)

```


```{r file_input, eval=TRUE}
file_url <- getURL("https://raw.githubusercontent.com/jey1987/DATA607/master/Week5_Assignment/Tidy_Input_Airlines_1.csv")
input_data <- data.frame(read.csv(text=file_url, header = TRUE),stringsAsFactors =FALSE)

```

## Tidying up the Input File

You can also embed plots, for example:

```{r file_tidy, eval=TRUE}
input_data <- na.omit(input_data)

input_data[2,1] <- as.character(input_data[1,1])
input_data[4,1] <- as.character(input_data[3,1])

names(input_data)[1] <- paste("Origin")
names(input_data)[2] <- paste("Status")

input_data  

```

## Aggregating the delayed airline 

```{r file_analyze, eval=TRUE}
input_data <- data.frame(filter(gather(input_data, "destination","n",3:7 ),Status == "delayed"),stringsAsFactors = FALSE) 

input_data


output_final <- input_data %>%
  group_by(Origin,Status) %>%
    summarize(sum_flights = sum(n)) 

output_final
```

## Displaying the final list who delays the flight frequently

```{r file_result, eval=TRUE}
output_final <- filter(output_final,sum_flights == min(output_final$sum_flights))  
output_final

```